### ISSUE TITLE
statbot: make it do *something* useful

### ISSUE THREAD

**Issue by jhgaylor** [jhgaylor/StatBot#2]

**Comment by jhgaylor** [comment]
- refer X friends to gain immediate access to the alpha
  - use referral codes that need to be sent to the bot using a command !alpha MYCODE
- bot should be always available. unregistered users should get some message about how to get started

**Comment by jhgaylor** [comment]
everything is up, but I'd also like to have a couple of useful commands working

**Comment by jhgaylor** [comment]
it does tell the list of free champions, but that is available in the launcher, so meh. Need to return something for which a gamer would have gone to a website.

**Comment by jhgaylor** [comment]
it _kinda_ does stats now. need to round that out and add one slightly more useful thing. stats isn't something most people look for spur of the moment (maybe full team, but not one at a time for sure)

**Comment by jhgaylor** [comment]
stats works entirely now.  with the introduction of the option parser, things should start getting interesting.

going to add a command `best <summoner> [<n> --role --season --region]` and its opposite, `worst <summoner> [<n> --role --season --region]`

**Comment by jhgaylor** [comment]
`links <champion>` - provides a set of useful links rather than going to each site and clicking to the champion desired.

`game <summoner>` - provide a lolnexus like overview of the game summoner is in

**Comment by togosh** [comment]
WOOT!

**Comment by jhgaylor** [comment]
I have a watcher! Welcome Stephen. Nice to have you here. i made `help` look good in game :sparkles:  you should check it out and determine if it is more usable

**Comment by jhgaylor** [comment]
I've moved all the ideas from here to individual issues to watch their progress more granularly.

**Comment by jhgaylor** [comment]
with the addition of the links command i consider this issue closed.
