### ISSUE TITLE
Feature Request: List all commands by themselves

### ISSUE THREAD

**Issue by togosh** [jhgaylor/StatBot#32]
Add ability to list all commands in one line, when I type help, I get full info and most commands scroll by.

Id like to be able to see this: 

counter,rules,help,free,stats

Probably in alphabetic order.

This could be another command or at the end of help.

**Comment by jhgaylor** [comment]
Done :) https://github.com/jhgaylor/StatBot/commit/e303661b936546c247c1c2f3d772cf346fbbe5ca#diff-e9ebc8fd39102ce10668c18ee7ecbdc4
